controller:
  jenkinsUrlProtocol: http
  jenkinsUriPrefix: /jenkins
  ingress:
    enabled: true
    annotations:
    hostName: ${hostname}
    path: /jenkins
  installPlugins: [kubernetes,workflow-aggregator,git,configuration-as-code,gitea]
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "${password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    configScripts:
      gitea-creds: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                - usernamePassword:
                    scope: SYSTEM
                    id: gitea
                    username: gitea_admin
                    password: "${password}"
      gitea: |
        unclassified:
          giteaServers:
            servers:
            - credentialsId: gitea
              displayName: gitea
              manageHooks: true
              serverUrl: http://gitea-http.default.svc.cluster.local:3000