controller:
  jenkinsUrlProtocol: http
  jenkinsUriPrefix: /jenkins
  ingress:
    enabled: true
    annotations:
    hostName: ${hostname}
    path: /jenkins
  installPlugins: [kubernetes,workflow-aggregator,git,configuration-as-code,gitea,terraform]
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "${password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    configScripts:
      gitea-creds: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                - usernamePassword:
                    scope: GLOBAL
                    id: gitea
                    username: gitea_admin
                    password: "${password}"
      gitea: |
        unclassified:
          giteaServers:
            servers:
            - credentialsId: gitea
              displayName: gitea
              manageHooks: true
              serverUrl: http://gitea-http.default.svc.cluster.local:3000
      terraform: |
        tool:
          terraform:
            installations:
              - name: "terraform"
                home: "/terraform-1.3.3"
                properties:
                  - installSource:
                      installers:
                        - terraformInstaller:
                            id: "1.3.3-linux-amd64"